// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Selos*
 */
export interface FooterDocumentDataSelosItem {
  /**
   * Selo field in *Footer → Selos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.selos[].selo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  selo: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Social Media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * Ícone social field in *Footer → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].social_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Link social field in *Footer → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Ex: https://www.instagram.com/alexandria.energia/
   * - **API ID Path**: footer.social_media[].social_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → Links Externos*
 */
export interface FooterDocumentDataLinksExternosItem {
  /**
   * Link field in *Footer → Links Externos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Ex: Politicas de privacidade
   * - **API ID Path**: footer.links_externos[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Imagem de background field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Selos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.selos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  selos: prismic.GroupField<Simplify<FooterDocumentDataSelosItem>>;

  /**
   * Titulo endereço field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Endereço
   * - **API ID Path**: footer.title_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_address: prismic.RichTextField;

  /**
   * Endereço field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: R. Fernando Amaro, 60 - Alto da XV, Curitiba - PR, 80045-080
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;

  /**
   * Titulo Social Media field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Siga a Alexandria nas redes sociais
   * - **API ID Path**: footer.social_media_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  social_media_title: prismic.RichTextField;

  /**
   * Social Media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * Texto de Copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: © 2025 Alexandria. Todos os direitos reservados.
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text: prismic.RichTextField;

  /**
   * Links Externos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_externos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links_externos: prismic.GroupField<
    Simplify<FooterDocumentDataLinksExternosItem>
  >;

  /**
   * Numero de suporte  field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: numero do WhtasApp
   * - **API ID Path**: footer.support_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  support_number: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Menu de navegaçao*
 */
export interface HeaderDocumentDataMenuNavigationItem {
  /**
   * Nome da âncora field in *Header → Menu de navegaçao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Exemplo: O que nos move
   * - **API ID Path**: header.menu_navigation[].anchor_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_name: prismic.KeyTextField;

  /**
   * Ancora de seçao field in *Header → Menu de navegaçao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Exemplo: #o-que-nos-move
   * - **API ID Path**: header.menu_navigation[].menu_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_item: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo  field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu de navegaçao field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.menu_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_navigation: prismic.GroupField<
    Simplify<HeaderDocumentDataMenuNavigationItem>
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | MapSectionSlice
  | CarouselSectionSlice
  | MockupSectionSlice
  | VideoSectionSlice
  | CtaSectionSlice
  | ZoomImagesSlice
  | BigTextSectionSlice
  | FeatureSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomepageDocument;

/**
 * Primary content in *BigTextSection → Default → Primary*
 */
export interface BigTextSectionSliceDefaultPrimary {
  /**
   * Imagem de fundo field in *BigTextSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_text_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Text field in *BigTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Simplificamos o que antes era complicado.
   * - **API ID Path**: big_text_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BigTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigTextSection*
 */
type BigTextSectionSliceVariation = BigTextSectionSliceDefault;

/**
 * BigTextSection Shared Slice
 *
 * - **API ID**: `big_text_section`
 * - **Description**: BigTextSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSectionSlice = prismic.SharedSlice<
  "big_text_section",
  BigTextSectionSliceVariation
>;

/**
 * Item in *CarouselSection → Default → Primary → Carrossel*
 */
export interface CarouselSectionSliceDefaultPrimaryCarouselItem {
  /**
   * Imagem field in *CarouselSection → Default → Primary → Carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo da imagem field in *CarouselSection → Default → Primary → Carrossel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Marcelino Eilert
   * - **API ID Path**: carousel_section.default.primary.carousel[].image_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_title: prismic.RichTextField;

  /**
   * Descrição da imagem field in *CarouselSection → Default → Primary → Carrossel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: CTO
   * - **API ID Path**: carousel_section.default.primary.carousel[].image_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_description: prismic.RichTextField;
}

/**
 * Primary content in *CarouselSection → Default → Primary*
 */
export interface CarouselSectionSliceDefaultPrimary {
  /**
   * Titulo da seçao field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição da seção field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Imagem de background field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.backgorund_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgorund_image: prismic.ImageField<never>;

  /**
   * Background animado field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.background_animated
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_animated: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Carrossel field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel: prismic.GroupField<
    Simplify<CarouselSectionSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for CarouselSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CarouselSection*
 */
type CarouselSectionSliceVariation = CarouselSectionSliceDefault;

/**
 * CarouselSection Shared Slice
 *
 * - **API ID**: `carousel_section`
 * - **Description**: CarouselSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSectionSlice = prismic.SharedSlice<
  "carousel_section",
  CarouselSectionSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Titulo field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Conheça a Lex
   * - **API ID Path**: cta_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto descritico da seçao
   * - **API ID Path**: cta_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Imagem de background field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *Feature → Default → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Imagem field in *Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Ttulo field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo da secao
   * - **API ID Path**: feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Animaçao de fundo da seçao field in *Feature → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: URL da midia de background
   * - **API ID Path**: feature.default.primary.background_animation
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_animation: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto de titulo do Hero
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto de descrição do Hero
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Insira o link do video
   * - **API ID Path**: hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  background_video: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MapSection → Default → Primary*
 */
export interface MapSectionSliceDefaultPrimary {
  /**
   * Titulo da seção  field in *MapSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Onde nós estamos?
   * - **API ID Path**: map_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto descritivo da seção  field in *MapSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Latitude field in *MapSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: -23.5505
   * - **API ID Path**: map_section.default.primary.latitude
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  latitude: prismic.KeyTextField;

  /**
   * Longitude field in *MapSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: -32.5602
   * - **API ID Path**: map_section.default.primary.longitude
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  longitude: prismic.KeyTextField;
}

/**
 * Default variation for MapSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MapSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MapSection*
 */
type MapSectionSliceVariation = MapSectionSliceDefault;

/**
 * MapSection Shared Slice
 *
 * - **API ID**: `map_section`
 * - **Description**: MapSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MapSectionSlice = prismic.SharedSlice<
  "map_section",
  MapSectionSliceVariation
>;

/**
 * Primary content in *MockupSection → Default → Primary*
 */
export interface MockupSectionSliceDefaultPrimary {
  /**
   * Titulo da seçao field in *MockupSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Por que a Alexandria?
   * - **API ID Path**: mockup_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitulo da seçao field in *MockupSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Infraestrutura própria
   * - **API ID Path**: mockup_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Texto descritivo da seçao field in *MockupSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Imagem do mockup primária field in *MockupSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup_section.default.primary.mockup_image_primary
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mockup_image_primary: prismic.ImageField<never>;

  /**
   * Imagem do mockup secondária field in *MockupSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup_section.default.primary.mockup_image_secondary
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mockup_image_secondary: prismic.ImageField<never>;
}

/**
 * Default variation for MockupSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MockupSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MockupSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MockupSection*
 */
type MockupSectionSliceVariation = MockupSectionSliceDefault;

/**
 * MockupSection Shared Slice
 *
 * - **API ID**: `mockup_section`
 * - **Description**: MockupSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MockupSectionSlice = prismic.SharedSlice<
  "mockup_section",
  MockupSectionSliceVariation
>;

/**
 * Primary content in *VideoSection → Default → Primary*
 */
export interface VideoSectionSliceDefaultPrimary {
  /**
   * Video field in *VideoSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Selecione o video em Media Library
   * - **API ID Path**: video_section.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Titulo da seçao field in *VideoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Nosso ecossistema
   * - **API ID Path**: video_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descriçao field in *VideoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Infraestrutura própria. Distribuição em rede. Dados como ativo
   * - **API ID Path**: video_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for VideoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoSection*
 */
type VideoSectionSliceVariation = VideoSectionSliceDefault;

/**
 * VideoSection Shared Slice
 *
 * - **API ID**: `video_section`
 * - **Description**: VideoSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSectionSlice = prismic.SharedSlice<
  "video_section",
  VideoSectionSliceVariation
>;

/**
 * Item in *ZoomImages → Default → Primary → Imagens*
 */
export interface ZoomImagesSliceDefaultPrimaryImagesItem {
  /**
   * Imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo da Imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Nosso Proposito
   * - **API ID Path**: zoom_images.default.primary.images[].image_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_title: prismic.RichTextField;

  /**
   * Descriçao da imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[].image_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_description: prismic.RichTextField;
}

/**
 * Primary content in *ZoomImages → Default → Primary*
 */
export interface ZoomImagesSliceDefaultPrimary {
  /**
   * Titulo field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo da seçao
   * - **API ID Path**: zoom_images.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto descritivo da seçao
   * - **API ID Path**: zoom_images.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Imagens field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ZoomImagesSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for ZoomImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ZoomImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ZoomImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ZoomImages*
 */
type ZoomImagesSliceVariation = ZoomImagesSliceDefault;

/**
 * ZoomImages Shared Slice
 *
 * - **API ID**: `zoom_images`
 * - **Description**: ZoomImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ZoomImagesSlice = prismic.SharedSlice<
  "zoom_images",
  ZoomImagesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSelosItem,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataLinksExternosItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataMenuNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BigTextSectionSlice,
      BigTextSectionSliceDefaultPrimary,
      BigTextSectionSliceVariation,
      BigTextSectionSliceDefault,
      CarouselSectionSlice,
      CarouselSectionSliceDefaultPrimaryCarouselItem,
      CarouselSectionSliceDefaultPrimary,
      CarouselSectionSliceVariation,
      CarouselSectionSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MapSectionSlice,
      MapSectionSliceDefaultPrimary,
      MapSectionSliceVariation,
      MapSectionSliceDefault,
      MockupSectionSlice,
      MockupSectionSliceDefaultPrimary,
      MockupSectionSliceVariation,
      MockupSectionSliceDefault,
      VideoSectionSlice,
      VideoSectionSliceDefaultPrimary,
      VideoSectionSliceVariation,
      VideoSectionSliceDefault,
      ZoomImagesSlice,
      ZoomImagesSliceDefaultPrimaryImagesItem,
      ZoomImagesSliceDefaultPrimary,
      ZoomImagesSliceVariation,
      ZoomImagesSliceDefault,
    };
  }
}
