// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Header → Menu de navegaçao*
 */
export interface HeaderDocumentDataMenuNavigationItem {
  /**
   * Nome da âncora field in *Header → Menu de navegaçao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Exemplo: O que nos move
   * - **API ID Path**: header.menu_navigation[].anchor_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_name: prismic.KeyTextField;

  /**
   * Ancora de seçao field in *Header → Menu de navegaçao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Exemplo: #o-que-nos-move
   * - **API ID Path**: header.menu_navigation[].menu_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_item: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo  field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu de navegaçao field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.menu_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_navigation: prismic.GroupField<
    Simplify<HeaderDocumentDataMenuNavigationItem>
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ZoomImagesSlice
  | BigTextSectionSlice
  | FeatureSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HeaderDocument | HomepageDocument;

/**
 * Primary content in *BigTextSection → Default → Primary*
 */
export interface BigTextSectionSliceDefaultPrimary {
  /**
   * Imagem de fundo field in *BigTextSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_text_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Text field in *BigTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Simplificamos o que antes era complicado.
   * - **API ID Path**: big_text_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BigTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigTextSection*
 */
type BigTextSectionSliceVariation = BigTextSectionSliceDefault;

/**
 * BigTextSection Shared Slice
 *
 * - **API ID**: `big_text_section`
 * - **Description**: BigTextSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSectionSlice = prismic.SharedSlice<
  "big_text_section",
  BigTextSectionSliceVariation
>;

/**
 * Primary content in *Feature → Default → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Imagem field in *Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Ttulo field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo da secao
   * - **API ID Path**: feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Animaçao de fundo da seçao field in *Feature → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: URL da midia de background
   * - **API ID Path**: feature.default.primary.background_animation
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_animation: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto de titulo do Hero
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto de descrição do Hero
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Insira o link do video
   * - **API ID Path**: hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  background_video: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ZoomImages → Default → Primary → Imagens*
 */
export interface ZoomImagesSliceDefaultPrimaryImagesItem {
  /**
   * Imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo da Imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Nosso Proposito
   * - **API ID Path**: zoom_images.default.primary.images[].image_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_title: prismic.RichTextField;

  /**
   * Descriçao da imagem field in *ZoomImages → Default → Primary → Imagens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[].image_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  image_description: prismic.RichTextField;
}

/**
 * Primary content in *ZoomImages → Default → Primary*
 */
export interface ZoomImagesSliceDefaultPrimary {
  /**
   * Titulo field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo da seçao
   * - **API ID Path**: zoom_images.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto descritivo da seçao
   * - **API ID Path**: zoom_images.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Imagens field in *ZoomImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: zoom_images.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ZoomImagesSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for ZoomImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ZoomImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ZoomImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ZoomImages*
 */
type ZoomImagesSliceVariation = ZoomImagesSliceDefault;

/**
 * ZoomImages Shared Slice
 *
 * - **API ID**: `zoom_images`
 * - **Description**: ZoomImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ZoomImagesSlice = prismic.SharedSlice<
  "zoom_images",
  ZoomImagesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataMenuNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BigTextSectionSlice,
      BigTextSectionSliceDefaultPrimary,
      BigTextSectionSliceVariation,
      BigTextSectionSliceDefault,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ZoomImagesSlice,
      ZoomImagesSliceDefaultPrimaryImagesItem,
      ZoomImagesSliceDefaultPrimary,
      ZoomImagesSliceVariation,
      ZoomImagesSliceDefault,
    };
  }
}
