import type { Metadata } from "next";
import { Baloo_2, Nunito } from "next/font/google";

import Footer from "@/components/footer";
import Header from "@/components/header";

import { createClient } from "@/prismicio";

import "./globals.css";

const baloo = Baloo_2({
  subsets: ["latin"],
  variable: "--font-baloo",
  display: "swap",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Alexandria Institucional",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const header = await client.getSingle("header");
  const footer = await client.getSingle("footer");

  return (
    <html
      lang="pt-BR"
      className={`${baloo.variable} ${nunito.variable} h-full antialiased bg-white`}
    >
      <body className="min-h-full flex flex-col">
        <Header data={header.data} />
        {children}
        <Footer data={footer.data} />
      </body>
    </html>
  );
}
